// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';
/**
 * @enum {number}
 */
export namespace SelfMessaging{
export enum ACLCommand{
  LIST= 0,
  PERMIT= 1,
  REVOKE= 2
};
}

/**
 * @enum {number}
 */
export namespace SelfMessaging{
export enum ErrType{
  ErrConnection= 0,
  ErrBadRequest= 1,
  ErrInternal= 2,
  ErrMessage= 3,
  ErrAuth= 4,
  ErrACL= 5
};
}

/**
 * @enum {number}
 */
export namespace SelfMessaging{
export enum MsgType{
  MSG= 0,
  ACK= 1,
  ERR= 2,
  AUTH= 3,
  ACL= 4
};
}

/**
 * @enum {number}
 */
export namespace SelfMessaging{
export enum MsgSubType{
  Unknown= 0,
  AuthenticationReq= 1,
  AuthenticationResp= 2,
  AuthenticationQRResp= 3,
  AuthenticationDeepLinkResp= 4,
  FactReq= 5,
  FactResp= 6,
  FactQRResp= 7,
  FactDeepLinkResp= 8,
  EmailSecurityCodeReq= 9,
  EmailSecurityCodeResp= 10,
  PhoneSecurityCodeReq= 11,
  PhoneSecurityCodeResp= 12,
  PhoneVerificationReq= 13,
  PhoneVerificationResp= 14,
  EmailVerificationReq= 15,
  EmailVerificationResp= 16,
  DocumentVerificationReq= 17,
  DocumentVerificationResp= 18
};
}

/**
 * @constructor
 */
export namespace SelfMessaging{
export class ACL {
  bb: flatbuffers.ByteBuffer|null = null;

  bb_pos:number = 0;
/**
 * @param number i
 * @param flatbuffers.ByteBuffer bb
 * @returns ACL
 */
__init(i:number, bb:flatbuffers.ByteBuffer):ACL {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param flatbuffers.ByteBuffer bb
 * @param ACL= obj
 * @returns ACL
 */
static getRootAsACL(bb:flatbuffers.ByteBuffer, obj?:ACL):ACL {
  return (obj || new ACL()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param flatbuffers.ByteBuffer bb
 * @param ACL= obj
 * @returns ACL
 */
static getSizePrefixedRootAsACL(bb:flatbuffers.ByteBuffer, obj?:ACL):ACL {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new ACL()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param flatbuffers.Encoding= optionalEncoding
 * @returns string|Uint8Array|null
 */
id():string|null
id(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
id(optionalEncoding?:any):string|Uint8Array|null {
  var offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @returns SelfMessaging.MsgType
 */
msgtype():SelfMessaging.MsgType {
  var offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? /**  */ (this.bb!.readInt8(this.bb_pos + offset)) : SelfMessaging.MsgType.MSG;
};

/**
 * @returns SelfMessaging.ACLCommand
 */
command():SelfMessaging.ACLCommand {
  var offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? /**  */ (this.bb!.readInt8(this.bb_pos + offset)) : SelfMessaging.ACLCommand.LIST;
};

/**
 * @param number index
 * @returns number
 */
payload(index: number):number|null {
  var offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.readUint8(this.bb!.__vector(this.bb_pos + offset) + index) : 0;
};

/**
 * @returns number
 */
payloadLength():number {
  var offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
};

/**
 * @returns Uint8Array
 */
payloadArray():Uint8Array|null {
  var offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? new Uint8Array(this.bb!.bytes().buffer, this.bb!.bytes().byteOffset + this.bb!.__vector(this.bb_pos + offset), this.bb!.__vector_len(this.bb_pos + offset)) : null;
};

/**
 * @param flatbuffers.Builder builder
 */
static startACL(builder:flatbuffers.Builder) {
  builder.startObject(4);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset idOffset
 */
static addId(builder:flatbuffers.Builder, idOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, idOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @param SelfMessaging.MsgType msgtype
 */
static addMsgtype(builder:flatbuffers.Builder, msgtype:SelfMessaging.MsgType) {
  builder.addFieldInt8(1, msgtype, SelfMessaging.MsgType.MSG);
};

/**
 * @param flatbuffers.Builder builder
 * @param SelfMessaging.ACLCommand command
 */
static addCommand(builder:flatbuffers.Builder, command:SelfMessaging.ACLCommand) {
  builder.addFieldInt8(2, command, SelfMessaging.ACLCommand.LIST);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset payloadOffset
 */
static addPayload(builder:flatbuffers.Builder, payloadOffset:flatbuffers.Offset) {
  builder.addFieldOffset(3, payloadOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @param Array.<number> data
 * @returns flatbuffers.Offset
 */
static createPayloadVector(builder:flatbuffers.Builder, data:number[]|Uint8Array):flatbuffers.Offset {
  builder.startVector(1, data.length, 1);
  for (var i = data.length - 1; i >= 0; i--) {
    builder.addInt8(data[i]);
  }
  return builder.endVector();
};

/**
 * @param flatbuffers.Builder builder
 * @param number numElems
 */
static startPayloadVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(1, numElems, 1);
};

/**
 * @param flatbuffers.Builder builder
 * @returns flatbuffers.Offset
 */
static endACL(builder:flatbuffers.Builder):flatbuffers.Offset {
  var offset = builder.endObject();
  return offset;
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset offset
 */
static finishACLBuffer(builder:flatbuffers.Builder, offset:flatbuffers.Offset) {
  builder.finish(offset);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset offset
 */
static finishSizePrefixedACLBuffer(builder:flatbuffers.Builder, offset:flatbuffers.Offset) {
  builder.finish(offset, undefined, true);
};

static createACL(builder:flatbuffers.Builder, idOffset:flatbuffers.Offset, msgtype:SelfMessaging.MsgType, command:SelfMessaging.ACLCommand, payloadOffset:flatbuffers.Offset):flatbuffers.Offset {
  ACL.startACL(builder);
  ACL.addId(builder, idOffset);
  ACL.addMsgtype(builder, msgtype);
  ACL.addCommand(builder, command);
  ACL.addPayload(builder, payloadOffset);
  return ACL.endACL(builder);
}
}
}
