"use strict";
// automatically generated by the FlatBuffers compiler, do not modify
exports.__esModule = true;
exports.SelfMessaging = void 0;
var flatbuffers = require("flatbuffers");
/**
 * @enum {number}
 */
var SelfMessaging;
(function (SelfMessaging) {
    var ACLCommand;
    (function (ACLCommand) {
        ACLCommand[ACLCommand["LIST"] = 0] = "LIST";
        ACLCommand[ACLCommand["PERMIT"] = 1] = "PERMIT";
        ACLCommand[ACLCommand["REVOKE"] = 2] = "REVOKE";
    })(ACLCommand = SelfMessaging.ACLCommand || (SelfMessaging.ACLCommand = {}));
    ;
})(SelfMessaging = exports.SelfMessaging || (exports.SelfMessaging = {}));
/**
 * @enum {number}
 */
(function (SelfMessaging) {
    var ErrType;
    (function (ErrType) {
        ErrType[ErrType["ErrConnection"] = 0] = "ErrConnection";
        ErrType[ErrType["ErrBadRequest"] = 1] = "ErrBadRequest";
        ErrType[ErrType["ErrInternal"] = 2] = "ErrInternal";
        ErrType[ErrType["ErrMessage"] = 3] = "ErrMessage";
        ErrType[ErrType["ErrAuth"] = 4] = "ErrAuth";
        ErrType[ErrType["ErrACL"] = 5] = "ErrACL";
    })(ErrType = SelfMessaging.ErrType || (SelfMessaging.ErrType = {}));
    ;
})(SelfMessaging = exports.SelfMessaging || (exports.SelfMessaging = {}));
/**
 * @enum {number}
 */
(function (SelfMessaging) {
    var MsgType;
    (function (MsgType) {
        MsgType[MsgType["MSG"] = 0] = "MSG";
        MsgType[MsgType["ACK"] = 1] = "ACK";
        MsgType[MsgType["ERR"] = 2] = "ERR";
        MsgType[MsgType["AUTH"] = 3] = "AUTH";
        MsgType[MsgType["ACL"] = 4] = "ACL";
    })(MsgType = SelfMessaging.MsgType || (SelfMessaging.MsgType = {}));
    ;
})(SelfMessaging = exports.SelfMessaging || (exports.SelfMessaging = {}));
/**
 * @enum {number}
 */
(function (SelfMessaging) {
    var MsgSubType;
    (function (MsgSubType) {
        MsgSubType[MsgSubType["Unknown"] = 0] = "Unknown";
        MsgSubType[MsgSubType["AuthenticationReq"] = 1] = "AuthenticationReq";
        MsgSubType[MsgSubType["AuthenticationResp"] = 2] = "AuthenticationResp";
        MsgSubType[MsgSubType["AuthenticationQRResp"] = 3] = "AuthenticationQRResp";
        MsgSubType[MsgSubType["AuthenticationDeepLinkResp"] = 4] = "AuthenticationDeepLinkResp";
        MsgSubType[MsgSubType["FactReq"] = 5] = "FactReq";
        MsgSubType[MsgSubType["FactResp"] = 6] = "FactResp";
        MsgSubType[MsgSubType["FactQRResp"] = 7] = "FactQRResp";
        MsgSubType[MsgSubType["FactDeepLinkResp"] = 8] = "FactDeepLinkResp";
        MsgSubType[MsgSubType["EmailSecurityCodeReq"] = 9] = "EmailSecurityCodeReq";
        MsgSubType[MsgSubType["EmailSecurityCodeResp"] = 10] = "EmailSecurityCodeResp";
        MsgSubType[MsgSubType["PhoneSecurityCodeReq"] = 11] = "PhoneSecurityCodeReq";
        MsgSubType[MsgSubType["PhoneSecurityCodeResp"] = 12] = "PhoneSecurityCodeResp";
        MsgSubType[MsgSubType["PhoneVerificationReq"] = 13] = "PhoneVerificationReq";
        MsgSubType[MsgSubType["PhoneVerificationResp"] = 14] = "PhoneVerificationResp";
        MsgSubType[MsgSubType["EmailVerificationReq"] = 15] = "EmailVerificationReq";
        MsgSubType[MsgSubType["EmailVerificationResp"] = 16] = "EmailVerificationResp";
        MsgSubType[MsgSubType["DocumentVerificationReq"] = 17] = "DocumentVerificationReq";
        MsgSubType[MsgSubType["DocumentVerificationResp"] = 18] = "DocumentVerificationResp";
    })(MsgSubType = SelfMessaging.MsgSubType || (SelfMessaging.MsgSubType = {}));
    ;
})(SelfMessaging = exports.SelfMessaging || (exports.SelfMessaging = {}));
/**
 * @constructor
 */
(function (SelfMessaging) {
    var ACL = /** @class */ (function () {
        function ACL() {
            this.bb = null;
            this.bb_pos = 0;
        }
        /**
         * @param number i
         * @param flatbuffers.ByteBuffer bb
         * @returns ACL
         */
        ACL.prototype.__init = function (i, bb) {
            this.bb_pos = i;
            this.bb = bb;
            return this;
        };
        ;
        /**
         * @param flatbuffers.ByteBuffer bb
         * @param ACL= obj
         * @returns ACL
         */
        ACL.getRootAsACL = function (bb, obj) {
            return (obj || new ACL()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
        };
        ;
        /**
         * @param flatbuffers.ByteBuffer bb
         * @param ACL= obj
         * @returns ACL
         */
        ACL.getSizePrefixedRootAsACL = function (bb, obj) {
            bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
            return (obj || new ACL()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
        };
        ;
        ACL.prototype.id = function (optionalEncoding) {
            var offset = this.bb.__offset(this.bb_pos, 4);
            return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
        };
        ;
        /**
         * @returns SelfMessaging.MsgType
         */
        ACL.prototype.msgtype = function () {
            var offset = this.bb.__offset(this.bb_pos, 6);
            return offset ? /**  */ (this.bb.readInt8(this.bb_pos + offset)) : SelfMessaging.MsgType.MSG;
        };
        ;
        /**
         * @returns SelfMessaging.ACLCommand
         */
        ACL.prototype.command = function () {
            var offset = this.bb.__offset(this.bb_pos, 8);
            return offset ? /**  */ (this.bb.readInt8(this.bb_pos + offset)) : SelfMessaging.ACLCommand.LIST;
        };
        ;
        /**
         * @param number index
         * @returns number
         */
        ACL.prototype.payload = function (index) {
            var offset = this.bb.__offset(this.bb_pos, 10);
            return offset ? this.bb.readUint8(this.bb.__vector(this.bb_pos + offset) + index) : 0;
        };
        ;
        /**
         * @returns number
         */
        ACL.prototype.payloadLength = function () {
            var offset = this.bb.__offset(this.bb_pos, 10);
            return offset ? this.bb.__vector_len(this.bb_pos + offset) : 0;
        };
        ;
        /**
         * @returns Uint8Array
         */
        ACL.prototype.payloadArray = function () {
            var offset = this.bb.__offset(this.bb_pos, 10);
            return offset ? new Uint8Array(this.bb.bytes().buffer, this.bb.bytes().byteOffset + this.bb.__vector(this.bb_pos + offset), this.bb.__vector_len(this.bb_pos + offset)) : null;
        };
        ;
        /**
         * @param flatbuffers.Builder builder
         */
        ACL.startACL = function (builder) {
            builder.startObject(4);
        };
        ;
        /**
         * @param flatbuffers.Builder builder
         * @param flatbuffers.Offset idOffset
         */
        ACL.addId = function (builder, idOffset) {
            builder.addFieldOffset(0, idOffset, 0);
        };
        ;
        /**
         * @param flatbuffers.Builder builder
         * @param SelfMessaging.MsgType msgtype
         */
        ACL.addMsgtype = function (builder, msgtype) {
            builder.addFieldInt8(1, msgtype, SelfMessaging.MsgType.MSG);
        };
        ;
        /**
         * @param flatbuffers.Builder builder
         * @param SelfMessaging.ACLCommand command
         */
        ACL.addCommand = function (builder, command) {
            builder.addFieldInt8(2, command, SelfMessaging.ACLCommand.LIST);
        };
        ;
        /**
         * @param flatbuffers.Builder builder
         * @param flatbuffers.Offset payloadOffset
         */
        ACL.addPayload = function (builder, payloadOffset) {
            builder.addFieldOffset(3, payloadOffset, 0);
        };
        ;
        /**
         * @param flatbuffers.Builder builder
         * @param Array.<number> data
         * @returns flatbuffers.Offset
         */
        ACL.createPayloadVector = function (builder, data) {
            builder.startVector(1, data.length, 1);
            for (var i = data.length - 1; i >= 0; i--) {
                builder.addInt8(data[i]);
            }
            return builder.endVector();
        };
        ;
        /**
         * @param flatbuffers.Builder builder
         * @param number numElems
         */
        ACL.startPayloadVector = function (builder, numElems) {
            builder.startVector(1, numElems, 1);
        };
        ;
        /**
         * @param flatbuffers.Builder builder
         * @returns flatbuffers.Offset
         */
        ACL.endACL = function (builder) {
            var offset = builder.endObject();
            return offset;
        };
        ;
        /**
         * @param flatbuffers.Builder builder
         * @param flatbuffers.Offset offset
         */
        ACL.finishACLBuffer = function (builder, offset) {
            builder.finish(offset);
        };
        ;
        /**
         * @param flatbuffers.Builder builder
         * @param flatbuffers.Offset offset
         */
        ACL.finishSizePrefixedACLBuffer = function (builder, offset) {
            builder.finish(offset, undefined, true);
        };
        ;
        ACL.createACL = function (builder, idOffset, msgtype, command, payloadOffset) {
            ACL.startACL(builder);
            ACL.addId(builder, idOffset);
            ACL.addMsgtype(builder, msgtype);
            ACL.addCommand(builder, command);
            ACL.addPayload(builder, payloadOffset);
            return ACL.endACL(builder);
        };
        return ACL;
    }());
    SelfMessaging.ACL = ACL;
})(SelfMessaging = exports.SelfMessaging || (exports.SelfMessaging = {}));
