"use strict";
// automatically generated by the FlatBuffers compiler, do not modify
exports.__esModule = true;
exports.SelfMessaging = void 0;
var flatbuffers = require("flatbuffers");
/**
 * @enum {number}
 */
var SelfMessaging;
(function (SelfMessaging) {
    var ACLCommand;
    (function (ACLCommand) {
        ACLCommand[ACLCommand["LIST"] = 0] = "LIST";
        ACLCommand[ACLCommand["PERMIT"] = 1] = "PERMIT";
        ACLCommand[ACLCommand["REVOKE"] = 2] = "REVOKE";
    })(ACLCommand = SelfMessaging.ACLCommand || (SelfMessaging.ACLCommand = {}));
    ;
})(SelfMessaging = exports.SelfMessaging || (exports.SelfMessaging = {}));
/**
 * @enum {number}
 */
(function (SelfMessaging) {
    var ErrType;
    (function (ErrType) {
        ErrType[ErrType["ErrConnection"] = 0] = "ErrConnection";
        ErrType[ErrType["ErrBadRequest"] = 1] = "ErrBadRequest";
        ErrType[ErrType["ErrInternal"] = 2] = "ErrInternal";
        ErrType[ErrType["ErrMessage"] = 3] = "ErrMessage";
        ErrType[ErrType["ErrAuth"] = 4] = "ErrAuth";
        ErrType[ErrType["ErrACL"] = 5] = "ErrACL";
    })(ErrType = SelfMessaging.ErrType || (SelfMessaging.ErrType = {}));
    ;
})(SelfMessaging = exports.SelfMessaging || (exports.SelfMessaging = {}));
/**
 * @enum {number}
 */
(function (SelfMessaging) {
    var MsgType;
    (function (MsgType) {
        MsgType[MsgType["MSG"] = 0] = "MSG";
        MsgType[MsgType["ACK"] = 1] = "ACK";
        MsgType[MsgType["ERR"] = 2] = "ERR";
        MsgType[MsgType["AUTH"] = 3] = "AUTH";
        MsgType[MsgType["ACL"] = 4] = "ACL";
    })(MsgType = SelfMessaging.MsgType || (SelfMessaging.MsgType = {}));
    ;
})(SelfMessaging = exports.SelfMessaging || (exports.SelfMessaging = {}));
/**
 * @enum {number}
 */
(function (SelfMessaging) {
    var MsgSubType;
    (function (MsgSubType) {
        MsgSubType[MsgSubType["Unknown"] = 0] = "Unknown";
        MsgSubType[MsgSubType["AuthenticationReq"] = 1] = "AuthenticationReq";
        MsgSubType[MsgSubType["AuthenticationResp"] = 2] = "AuthenticationResp";
        MsgSubType[MsgSubType["AuthenticationQRResp"] = 3] = "AuthenticationQRResp";
        MsgSubType[MsgSubType["AuthenticationDeepLinkResp"] = 4] = "AuthenticationDeepLinkResp";
        MsgSubType[MsgSubType["FactReq"] = 5] = "FactReq";
        MsgSubType[MsgSubType["FactResp"] = 6] = "FactResp";
        MsgSubType[MsgSubType["FactQRResp"] = 7] = "FactQRResp";
        MsgSubType[MsgSubType["FactDeepLinkResp"] = 8] = "FactDeepLinkResp";
        MsgSubType[MsgSubType["EmailSecurityCodeReq"] = 9] = "EmailSecurityCodeReq";
        MsgSubType[MsgSubType["EmailSecurityCodeResp"] = 10] = "EmailSecurityCodeResp";
        MsgSubType[MsgSubType["PhoneSecurityCodeReq"] = 11] = "PhoneSecurityCodeReq";
        MsgSubType[MsgSubType["PhoneSecurityCodeResp"] = 12] = "PhoneSecurityCodeResp";
        MsgSubType[MsgSubType["PhoneVerificationReq"] = 13] = "PhoneVerificationReq";
        MsgSubType[MsgSubType["PhoneVerificationResp"] = 14] = "PhoneVerificationResp";
        MsgSubType[MsgSubType["EmailVerificationReq"] = 15] = "EmailVerificationReq";
        MsgSubType[MsgSubType["EmailVerificationResp"] = 16] = "EmailVerificationResp";
        MsgSubType[MsgSubType["DocumentVerificationReq"] = 17] = "DocumentVerificationReq";
        MsgSubType[MsgSubType["DocumentVerificationResp"] = 18] = "DocumentVerificationResp";
    })(MsgSubType = SelfMessaging.MsgSubType || (SelfMessaging.MsgSubType = {}));
    ;
})(SelfMessaging = exports.SelfMessaging || (exports.SelfMessaging = {}));
/**
 * @constructor
 */
(function (SelfMessaging) {
    var Auth = /** @class */ (function () {
        function Auth() {
            this.bb = null;
            this.bb_pos = 0;
        }
        /**
         * @param number i
         * @param flatbuffers.ByteBuffer bb
         * @returns Auth
         */
        Auth.prototype.__init = function (i, bb) {
            this.bb_pos = i;
            this.bb = bb;
            return this;
        };
        ;
        /**
         * @param flatbuffers.ByteBuffer bb
         * @param Auth= obj
         * @returns Auth
         */
        Auth.getRootAsAuth = function (bb, obj) {
            return (obj || new Auth()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
        };
        ;
        /**
         * @param flatbuffers.ByteBuffer bb
         * @param Auth= obj
         * @returns Auth
         */
        Auth.getSizePrefixedRootAsAuth = function (bb, obj) {
            bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
            return (obj || new Auth()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
        };
        ;
        Auth.prototype.id = function (optionalEncoding) {
            var offset = this.bb.__offset(this.bb_pos, 4);
            return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
        };
        ;
        /**
         * @returns SelfMessaging.MsgType
         */
        Auth.prototype.msgtype = function () {
            var offset = this.bb.__offset(this.bb_pos, 6);
            return offset ? /**  */ (this.bb.readInt8(this.bb_pos + offset)) : SelfMessaging.MsgType.MSG;
        };
        ;
        Auth.prototype.token = function (optionalEncoding) {
            var offset = this.bb.__offset(this.bb_pos, 8);
            return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
        };
        ;
        Auth.prototype.device = function (optionalEncoding) {
            var offset = this.bb.__offset(this.bb_pos, 10);
            return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
        };
        ;
        /**
         * @returns flatbuffers.Long
         */
        Auth.prototype.offset = function () {
            var offset = this.bb.__offset(this.bb_pos, 12);
            return offset ? this.bb.readInt64(this.bb_pos + offset) : this.bb.createLong(0, 0);
        };
        ;
        /**
         * @param flatbuffers.Builder builder
         */
        Auth.startAuth = function (builder) {
            builder.startObject(5);
        };
        ;
        /**
         * @param flatbuffers.Builder builder
         * @param flatbuffers.Offset idOffset
         */
        Auth.addId = function (builder, idOffset) {
            builder.addFieldOffset(0, idOffset, 0);
        };
        ;
        /**
         * @param flatbuffers.Builder builder
         * @param SelfMessaging.MsgType msgtype
         */
        Auth.addMsgtype = function (builder, msgtype) {
            builder.addFieldInt8(1, msgtype, SelfMessaging.MsgType.MSG);
        };
        ;
        /**
         * @param flatbuffers.Builder builder
         * @param flatbuffers.Offset tokenOffset
         */
        Auth.addToken = function (builder, tokenOffset) {
            builder.addFieldOffset(2, tokenOffset, 0);
        };
        ;
        /**
         * @param flatbuffers.Builder builder
         * @param flatbuffers.Offset deviceOffset
         */
        Auth.addDevice = function (builder, deviceOffset) {
            builder.addFieldOffset(3, deviceOffset, 0);
        };
        ;
        /**
         * @param flatbuffers.Builder builder
         * @param flatbuffers.Long offset
         */
        Auth.addOffset = function (builder, offset) {
            builder.addFieldInt64(4, offset, builder.createLong(0, 0));
        };
        ;
        /**
         * @param flatbuffers.Builder builder
         * @returns flatbuffers.Offset
         */
        Auth.endAuth = function (builder) {
            var offset = builder.endObject();
            return offset;
        };
        ;
        /**
         * @param flatbuffers.Builder builder
         * @param flatbuffers.Offset offset
         */
        Auth.finishAuthBuffer = function (builder, offset) {
            builder.finish(offset);
        };
        ;
        /**
         * @param flatbuffers.Builder builder
         * @param flatbuffers.Offset offset
         */
        Auth.finishSizePrefixedAuthBuffer = function (builder, offset) {
            builder.finish(offset, undefined, true);
        };
        ;
        Auth.createAuth = function (builder, idOffset, msgtype, tokenOffset, deviceOffset, offset) {
            Auth.startAuth(builder);
            Auth.addId(builder, idOffset);
            Auth.addMsgtype(builder, msgtype);
            Auth.addToken(builder, tokenOffset);
            Auth.addDevice(builder, deviceOffset);
            Auth.addOffset(builder, offset);
            return Auth.endAuth(builder);
        };
        return Auth;
    }());
    SelfMessaging.Auth = Auth;
})(SelfMessaging = exports.SelfMessaging || (exports.SelfMessaging = {}));
