// automatically generated by the FlatBuffers compiler, do not modify

export enum ErrType{
  ErrConnection = 0,
  ErrBadRequest = 1,
  ErrInternal = 2,
  ErrMessage = 3,
  ErrAuth = 4,
  ErrWatch = 6
}

