// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';
/**
 * @enum {number}
 */
export namespace SelfMessaging{
export enum ACLCommand{
  LIST= 0,
  PERMIT= 1,
  REVOKE= 2
};
}

/**
 * @enum {number}
 */
export namespace SelfMessaging{
export enum ErrType{
  ErrConnection= 0,
  ErrBadRequest= 1,
  ErrInternal= 2,
  ErrMessage= 3,
  ErrAuth= 4,
  ErrACL= 5
};
}

/**
 * @enum {number}
 */
export namespace SelfMessaging{
export enum MsgType{
  MSG= 0,
  ACK= 1,
  ERR= 2,
  AUTH= 3,
  ACL= 4
};
}

/**
 * @enum {number}
 */
export namespace SelfMessaging{
export enum MsgSubType{
  Unknown= 0,
  AuthenticationReq= 1,
  AuthenticationResp= 2,
  AuthenticationQRResp= 3,
  AuthenticationDeepLinkResp= 4,
  FactReq= 5,
  FactResp= 6,
  FactQRResp= 7,
  FactDeepLinkResp= 8,
  EmailSecurityCodeReq= 9,
  EmailSecurityCodeResp= 10,
  PhoneSecurityCodeReq= 11,
  PhoneSecurityCodeResp= 12,
  PhoneVerificationReq= 13,
  PhoneVerificationResp= 14,
  EmailVerificationReq= 15,
  EmailVerificationResp= 16,
  DocumentVerificationReq= 17,
  DocumentVerificationResp= 18
};
}

/**
 * @constructor
 */
export namespace SelfMessaging{
export class Metadata {
  bb: flatbuffers.ByteBuffer|null = null;

  bb_pos:number = 0;
/**
 * @param number i
 * @param flatbuffers.ByteBuffer bb
 * @returns Metadata
 */
__init(i:number, bb:flatbuffers.ByteBuffer):Metadata {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @returns flatbuffers.Long
 */
timestamp():flatbuffers.Long {
  return this.bb!.readInt64(this.bb_pos);
};

/**
 * @returns flatbuffers.Long
 */
offset():flatbuffers.Long {
  return this.bb!.readInt64(this.bb_pos + 8);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Long timestamp
 * @param flatbuffers.Long offset
 * @returns flatbuffers.Offset
 */
static createMetadata(builder:flatbuffers.Builder, timestamp: flatbuffers.Long, offset: flatbuffers.Long):flatbuffers.Offset {
  builder.prep(8, 16);
  builder.writeInt64(offset);
  builder.writeInt64(timestamp);
  return builder.offset();
};

}
}
/**
 * @constructor
 */
export namespace SelfMessaging{
export class Message {
  bb: flatbuffers.ByteBuffer|null = null;

  bb_pos:number = 0;
/**
 * @param number i
 * @param flatbuffers.ByteBuffer bb
 * @returns Message
 */
__init(i:number, bb:flatbuffers.ByteBuffer):Message {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param flatbuffers.ByteBuffer bb
 * @param Message= obj
 * @returns Message
 */
static getRootAsMessage(bb:flatbuffers.ByteBuffer, obj?:Message):Message {
  return (obj || new Message()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param flatbuffers.ByteBuffer bb
 * @param Message= obj
 * @returns Message
 */
static getSizePrefixedRootAsMessage(bb:flatbuffers.ByteBuffer, obj?:Message):Message {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new Message()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param flatbuffers.Encoding= optionalEncoding
 * @returns string|Uint8Array|null
 */
id():string|null
id(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
id(optionalEncoding?:any):string|Uint8Array|null {
  var offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @returns SelfMessaging.MsgType
 */
msgtype():SelfMessaging.MsgType {
  var offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? /**  */ (this.bb!.readInt8(this.bb_pos + offset)) : SelfMessaging.MsgType.MSG;
};

/**
 * @returns SelfMessaging.MsgSubType
 */
subtype():SelfMessaging.MsgSubType {
  var offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? /**  */ (this.bb!.readUint16(this.bb_pos + offset)) : SelfMessaging.MsgSubType.Unknown;
};

/**
 * @param flatbuffers.Encoding= optionalEncoding
 * @returns string|Uint8Array|null
 */
sender():string|null
sender(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
sender(optionalEncoding?:any):string|Uint8Array|null {
  var offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param flatbuffers.Encoding= optionalEncoding
 * @returns string|Uint8Array|null
 */
recipient():string|null
recipient(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
recipient(optionalEncoding?:any):string|Uint8Array|null {
  var offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param SelfMessaging.Metadata= obj
 * @returns SelfMessaging.Metadata|null
 */
metadata(obj?:SelfMessaging.Metadata):SelfMessaging.Metadata|null {
  var offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? (obj || new SelfMessaging.Metadata()).__init(this.bb_pos + offset, this.bb!) : null;
};

/**
 * @param number index
 * @returns number
 */
ciphertext(index: number):number|null {
  var offset = this.bb!.__offset(this.bb_pos, 16);
  return offset ? this.bb!.readUint8(this.bb!.__vector(this.bb_pos + offset) + index) : 0;
};

/**
 * @returns number
 */
ciphertextLength():number {
  var offset = this.bb!.__offset(this.bb_pos, 16);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
};

/**
 * @returns Uint8Array
 */
ciphertextArray():Uint8Array|null {
  var offset = this.bb!.__offset(this.bb_pos, 16);
  return offset ? new Uint8Array(this.bb!.bytes().buffer, this.bb!.bytes().byteOffset + this.bb!.__vector(this.bb_pos + offset), this.bb!.__vector_len(this.bb_pos + offset)) : null;
};

/**
 * @param flatbuffers.Builder builder
 */
static startMessage(builder:flatbuffers.Builder) {
  builder.startObject(7);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset idOffset
 */
static addId(builder:flatbuffers.Builder, idOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, idOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @param SelfMessaging.MsgType msgtype
 */
static addMsgtype(builder:flatbuffers.Builder, msgtype:SelfMessaging.MsgType) {
  builder.addFieldInt8(1, msgtype, SelfMessaging.MsgType.MSG);
};

/**
 * @param flatbuffers.Builder builder
 * @param SelfMessaging.MsgSubType subtype
 */
static addSubtype(builder:flatbuffers.Builder, subtype:SelfMessaging.MsgSubType) {
  builder.addFieldInt16(2, subtype, SelfMessaging.MsgSubType.Unknown);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset senderOffset
 */
static addSender(builder:flatbuffers.Builder, senderOffset:flatbuffers.Offset) {
  builder.addFieldOffset(3, senderOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset recipientOffset
 */
static addRecipient(builder:flatbuffers.Builder, recipientOffset:flatbuffers.Offset) {
  builder.addFieldOffset(4, recipientOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset metadataOffset
 */
static addMetadata(builder:flatbuffers.Builder, metadataOffset:flatbuffers.Offset) {
  builder.addFieldStruct(5, metadataOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset ciphertextOffset
 */
static addCiphertext(builder:flatbuffers.Builder, ciphertextOffset:flatbuffers.Offset) {
  builder.addFieldOffset(6, ciphertextOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @param Array.<number> data
 * @returns flatbuffers.Offset
 */
static createCiphertextVector(builder:flatbuffers.Builder, data:number[]|Uint8Array):flatbuffers.Offset {
  builder.startVector(1, data.length, 1);
  for (var i = data.length - 1; i >= 0; i--) {
    builder.addInt8(data[i]);
  }
  return builder.endVector();
};

/**
 * @param flatbuffers.Builder builder
 * @param number numElems
 */
static startCiphertextVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(1, numElems, 1);
};

/**
 * @param flatbuffers.Builder builder
 * @returns flatbuffers.Offset
 */
static endMessage(builder:flatbuffers.Builder):flatbuffers.Offset {
  var offset = builder.endObject();
  builder.requiredField(offset, 14); // metadata
  return offset;
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset offset
 */
static finishMessageBuffer(builder:flatbuffers.Builder, offset:flatbuffers.Offset) {
  builder.finish(offset);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset offset
 */
static finishSizePrefixedMessageBuffer(builder:flatbuffers.Builder, offset:flatbuffers.Offset) {
  builder.finish(offset, undefined, true);
};

}
}
