"use strict";
// automatically generated by the FlatBuffers compiler, do not modify
exports.__esModule = true;
exports.SelfMessaging = void 0;
var flatbuffers = require("flatbuffers");
/**
 * @enum {number}
 */
var SelfMessaging;
(function (SelfMessaging) {
    var ACLCommand;
    (function (ACLCommand) {
        ACLCommand[ACLCommand["LIST"] = 0] = "LIST";
        ACLCommand[ACLCommand["PERMIT"] = 1] = "PERMIT";
        ACLCommand[ACLCommand["REVOKE"] = 2] = "REVOKE";
    })(ACLCommand = SelfMessaging.ACLCommand || (SelfMessaging.ACLCommand = {}));
    ;
})(SelfMessaging = exports.SelfMessaging || (exports.SelfMessaging = {}));
/**
 * @enum {number}
 */
(function (SelfMessaging) {
    var ErrType;
    (function (ErrType) {
        ErrType[ErrType["ErrConnection"] = 0] = "ErrConnection";
        ErrType[ErrType["ErrBadRequest"] = 1] = "ErrBadRequest";
        ErrType[ErrType["ErrInternal"] = 2] = "ErrInternal";
        ErrType[ErrType["ErrMessage"] = 3] = "ErrMessage";
        ErrType[ErrType["ErrAuth"] = 4] = "ErrAuth";
        ErrType[ErrType["ErrACL"] = 5] = "ErrACL";
    })(ErrType = SelfMessaging.ErrType || (SelfMessaging.ErrType = {}));
    ;
})(SelfMessaging = exports.SelfMessaging || (exports.SelfMessaging = {}));
/**
 * @enum {number}
 */
(function (SelfMessaging) {
    var MsgType;
    (function (MsgType) {
        MsgType[MsgType["MSG"] = 0] = "MSG";
        MsgType[MsgType["ACK"] = 1] = "ACK";
        MsgType[MsgType["ERR"] = 2] = "ERR";
        MsgType[MsgType["AUTH"] = 3] = "AUTH";
        MsgType[MsgType["ACL"] = 4] = "ACL";
    })(MsgType = SelfMessaging.MsgType || (SelfMessaging.MsgType = {}));
    ;
})(SelfMessaging = exports.SelfMessaging || (exports.SelfMessaging = {}));
/**
 * @enum {number}
 */
(function (SelfMessaging) {
    var MsgSubType;
    (function (MsgSubType) {
        MsgSubType[MsgSubType["Unknown"] = 0] = "Unknown";
        MsgSubType[MsgSubType["AuthenticationReq"] = 1] = "AuthenticationReq";
        MsgSubType[MsgSubType["AuthenticationResp"] = 2] = "AuthenticationResp";
        MsgSubType[MsgSubType["AuthenticationQRResp"] = 3] = "AuthenticationQRResp";
        MsgSubType[MsgSubType["AuthenticationDeepLinkResp"] = 4] = "AuthenticationDeepLinkResp";
        MsgSubType[MsgSubType["FactReq"] = 5] = "FactReq";
        MsgSubType[MsgSubType["FactResp"] = 6] = "FactResp";
        MsgSubType[MsgSubType["FactQRResp"] = 7] = "FactQRResp";
        MsgSubType[MsgSubType["FactDeepLinkResp"] = 8] = "FactDeepLinkResp";
        MsgSubType[MsgSubType["EmailSecurityCodeReq"] = 9] = "EmailSecurityCodeReq";
        MsgSubType[MsgSubType["EmailSecurityCodeResp"] = 10] = "EmailSecurityCodeResp";
        MsgSubType[MsgSubType["PhoneSecurityCodeReq"] = 11] = "PhoneSecurityCodeReq";
        MsgSubType[MsgSubType["PhoneSecurityCodeResp"] = 12] = "PhoneSecurityCodeResp";
        MsgSubType[MsgSubType["PhoneVerificationReq"] = 13] = "PhoneVerificationReq";
        MsgSubType[MsgSubType["PhoneVerificationResp"] = 14] = "PhoneVerificationResp";
        MsgSubType[MsgSubType["EmailVerificationReq"] = 15] = "EmailVerificationReq";
        MsgSubType[MsgSubType["EmailVerificationResp"] = 16] = "EmailVerificationResp";
        MsgSubType[MsgSubType["DocumentVerificationReq"] = 17] = "DocumentVerificationReq";
        MsgSubType[MsgSubType["DocumentVerificationResp"] = 18] = "DocumentVerificationResp";
    })(MsgSubType = SelfMessaging.MsgSubType || (SelfMessaging.MsgSubType = {}));
    ;
})(SelfMessaging = exports.SelfMessaging || (exports.SelfMessaging = {}));
/**
 * @constructor
 */
(function (SelfMessaging) {
    var Metadata = /** @class */ (function () {
        function Metadata() {
            this.bb = null;
            this.bb_pos = 0;
        }
        /**
         * @param number i
         * @param flatbuffers.ByteBuffer bb
         * @returns Metadata
         */
        Metadata.prototype.__init = function (i, bb) {
            this.bb_pos = i;
            this.bb = bb;
            return this;
        };
        ;
        /**
         * @returns flatbuffers.Long
         */
        Metadata.prototype.timestamp = function () {
            return this.bb.readInt64(this.bb_pos);
        };
        ;
        /**
         * @returns flatbuffers.Long
         */
        Metadata.prototype.offset = function () {
            return this.bb.readInt64(this.bb_pos + 8);
        };
        ;
        /**
         * @param flatbuffers.Builder builder
         * @param flatbuffers.Long timestamp
         * @param flatbuffers.Long offset
         * @returns flatbuffers.Offset
         */
        Metadata.createMetadata = function (builder, timestamp, offset) {
            builder.prep(8, 16);
            builder.writeInt64(offset);
            builder.writeInt64(timestamp);
            return builder.offset();
        };
        ;
        return Metadata;
    }());
    SelfMessaging.Metadata = Metadata;
})(SelfMessaging = exports.SelfMessaging || (exports.SelfMessaging = {}));
/**
 * @constructor
 */
(function (SelfMessaging) {
    var Message = /** @class */ (function () {
        function Message() {
            this.bb = null;
            this.bb_pos = 0;
        }
        /**
         * @param number i
         * @param flatbuffers.ByteBuffer bb
         * @returns Message
         */
        Message.prototype.__init = function (i, bb) {
            this.bb_pos = i;
            this.bb = bb;
            return this;
        };
        ;
        /**
         * @param flatbuffers.ByteBuffer bb
         * @param Message= obj
         * @returns Message
         */
        Message.getRootAsMessage = function (bb, obj) {
            return (obj || new Message()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
        };
        ;
        /**
         * @param flatbuffers.ByteBuffer bb
         * @param Message= obj
         * @returns Message
         */
        Message.getSizePrefixedRootAsMessage = function (bb, obj) {
            bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
            return (obj || new Message()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
        };
        ;
        Message.prototype.id = function (optionalEncoding) {
            var offset = this.bb.__offset(this.bb_pos, 4);
            return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
        };
        ;
        /**
         * @returns SelfMessaging.MsgType
         */
        Message.prototype.msgtype = function () {
            var offset = this.bb.__offset(this.bb_pos, 6);
            return offset ? /**  */ (this.bb.readInt8(this.bb_pos + offset)) : SelfMessaging.MsgType.MSG;
        };
        ;
        /**
         * @returns SelfMessaging.MsgSubType
         */
        Message.prototype.subtype = function () {
            var offset = this.bb.__offset(this.bb_pos, 8);
            return offset ? /**  */ (this.bb.readUint16(this.bb_pos + offset)) : SelfMessaging.MsgSubType.Unknown;
        };
        ;
        Message.prototype.sender = function (optionalEncoding) {
            var offset = this.bb.__offset(this.bb_pos, 10);
            return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
        };
        ;
        Message.prototype.recipient = function (optionalEncoding) {
            var offset = this.bb.__offset(this.bb_pos, 12);
            return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
        };
        ;
        /**
         * @param SelfMessaging.Metadata= obj
         * @returns SelfMessaging.Metadata|null
         */
        Message.prototype.metadata = function (obj) {
            var offset = this.bb.__offset(this.bb_pos, 14);
            return offset ? (obj || new SelfMessaging.Metadata()).__init(this.bb_pos + offset, this.bb) : null;
        };
        ;
        /**
         * @param number index
         * @returns number
         */
        Message.prototype.ciphertext = function (index) {
            var offset = this.bb.__offset(this.bb_pos, 16);
            return offset ? this.bb.readUint8(this.bb.__vector(this.bb_pos + offset) + index) : 0;
        };
        ;
        /**
         * @returns number
         */
        Message.prototype.ciphertextLength = function () {
            var offset = this.bb.__offset(this.bb_pos, 16);
            return offset ? this.bb.__vector_len(this.bb_pos + offset) : 0;
        };
        ;
        /**
         * @returns Uint8Array
         */
        Message.prototype.ciphertextArray = function () {
            var offset = this.bb.__offset(this.bb_pos, 16);
            return offset ? new Uint8Array(this.bb.bytes().buffer, this.bb.bytes().byteOffset + this.bb.__vector(this.bb_pos + offset), this.bb.__vector_len(this.bb_pos + offset)) : null;
        };
        ;
        /**
         * @param flatbuffers.Builder builder
         */
        Message.startMessage = function (builder) {
            builder.startObject(7);
        };
        ;
        /**
         * @param flatbuffers.Builder builder
         * @param flatbuffers.Offset idOffset
         */
        Message.addId = function (builder, idOffset) {
            builder.addFieldOffset(0, idOffset, 0);
        };
        ;
        /**
         * @param flatbuffers.Builder builder
         * @param SelfMessaging.MsgType msgtype
         */
        Message.addMsgtype = function (builder, msgtype) {
            builder.addFieldInt8(1, msgtype, SelfMessaging.MsgType.MSG);
        };
        ;
        /**
         * @param flatbuffers.Builder builder
         * @param SelfMessaging.MsgSubType subtype
         */
        Message.addSubtype = function (builder, subtype) {
            builder.addFieldInt16(2, subtype, SelfMessaging.MsgSubType.Unknown);
        };
        ;
        /**
         * @param flatbuffers.Builder builder
         * @param flatbuffers.Offset senderOffset
         */
        Message.addSender = function (builder, senderOffset) {
            builder.addFieldOffset(3, senderOffset, 0);
        };
        ;
        /**
         * @param flatbuffers.Builder builder
         * @param flatbuffers.Offset recipientOffset
         */
        Message.addRecipient = function (builder, recipientOffset) {
            builder.addFieldOffset(4, recipientOffset, 0);
        };
        ;
        /**
         * @param flatbuffers.Builder builder
         * @param flatbuffers.Offset metadataOffset
         */
        Message.addMetadata = function (builder, metadataOffset) {
            builder.addFieldStruct(5, metadataOffset, 0);
        };
        ;
        /**
         * @param flatbuffers.Builder builder
         * @param flatbuffers.Offset ciphertextOffset
         */
        Message.addCiphertext = function (builder, ciphertextOffset) {
            builder.addFieldOffset(6, ciphertextOffset, 0);
        };
        ;
        /**
         * @param flatbuffers.Builder builder
         * @param Array.<number> data
         * @returns flatbuffers.Offset
         */
        Message.createCiphertextVector = function (builder, data) {
            builder.startVector(1, data.length, 1);
            for (var i = data.length - 1; i >= 0; i--) {
                builder.addInt8(data[i]);
            }
            return builder.endVector();
        };
        ;
        /**
         * @param flatbuffers.Builder builder
         * @param number numElems
         */
        Message.startCiphertextVector = function (builder, numElems) {
            builder.startVector(1, numElems, 1);
        };
        ;
        /**
         * @param flatbuffers.Builder builder
         * @returns flatbuffers.Offset
         */
        Message.endMessage = function (builder) {
            var offset = builder.endObject();
            builder.requiredField(offset, 14); // metadata
            return offset;
        };
        ;
        /**
         * @param flatbuffers.Builder builder
         * @param flatbuffers.Offset offset
         */
        Message.finishMessageBuffer = function (builder, offset) {
            builder.finish(offset);
        };
        ;
        /**
         * @param flatbuffers.Builder builder
         * @param flatbuffers.Offset offset
         */
        Message.finishSizePrefixedMessageBuffer = function (builder, offset) {
            builder.finish(offset, undefined, true);
        };
        ;
        return Message;
    }());
    SelfMessaging.Message = Message;
})(SelfMessaging = exports.SelfMessaging || (exports.SelfMessaging = {}));
