// automatically generated by the FlatBuffers compiler, do not modify

export enum MsgSubType{
  Unknown = 0,
  AuthenticationReq = 1,
  AuthenticationResp = 2,
  AuthenticationQRResp = 3,
  AuthenticationDeepLinkResp = 4,
  FactReq = 5,
  FactResp = 6,
  FactQRResp = 7,
  FactDeepLinkResp = 8,
  EmailSecurityCodeReq = 9,
  EmailSecurityCodeResp = 10,
  PhoneSecurityCodeReq = 11,
  PhoneSecurityCodeResp = 12,
  PhoneVerificationReq = 13,
  PhoneVerificationResp = 14,
  EmailVerificationReq = 15,
  EmailVerificationResp = 16,
  DocumentVerificationReq = 17,
  DocumentVerificationResp = 18
}

