// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

import { ErrType } from '../msgproto/err-type';
import { MsgType } from '../msgproto/msg-type';


export class Notification {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
__init(i:number, bb:flatbuffers.ByteBuffer):Notification {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsNotification(bb:flatbuffers.ByteBuffer, obj?:Notification):Notification {
  return (obj || new Notification()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsNotification(bb:flatbuffers.ByteBuffer, obj?:Notification):Notification {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new Notification()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

id():string|null
id(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
id(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

msgtype():MsgType {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readInt8(this.bb_pos + offset) : MsgType.MSG;
}

error():string|null
error(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
error(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

errtype():ErrType {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.readInt8(this.bb_pos + offset) : ErrType.ErrConnection;
}

static startNotification(builder:flatbuffers.Builder) {
  builder.startObject(4);
}

static addId(builder:flatbuffers.Builder, idOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, idOffset, 0);
}

static addMsgtype(builder:flatbuffers.Builder, msgtype:MsgType) {
  builder.addFieldInt8(1, msgtype, MsgType.MSG);
}

static addError(builder:flatbuffers.Builder, errorOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, errorOffset, 0);
}

static addErrtype(builder:flatbuffers.Builder, errtype:ErrType) {
  builder.addFieldInt8(3, errtype, ErrType.ErrConnection);
}

static endNotification(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static finishNotificationBuffer(builder:flatbuffers.Builder, offset:flatbuffers.Offset) {
  builder.finish(offset);
}

static finishSizePrefixedNotificationBuffer(builder:flatbuffers.Builder, offset:flatbuffers.Offset) {
  builder.finish(offset, undefined, true);
}

static createNotification(builder:flatbuffers.Builder, idOffset:flatbuffers.Offset, msgtype:MsgType, errorOffset:flatbuffers.Offset, errtype:ErrType):flatbuffers.Offset {
  Notification.startNotification(builder);
  Notification.addId(builder, idOffset);
  Notification.addMsgtype(builder, msgtype);
  Notification.addError(builder, errorOffset);
  Notification.addErrtype(builder, errtype);
  return Notification.endNotification(builder);
}
}
