// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';
/**
 * @enum {number}
 */
export namespace SelfMessaging{
export enum ACLCommand{
  LIST= 0,
  PERMIT= 1,
  REVOKE= 2
};
}

/**
 * @enum {number}
 */
export namespace SelfMessaging{
export enum ErrType{
  ErrConnection= 0,
  ErrBadRequest= 1,
  ErrInternal= 2,
  ErrMessage= 3,
  ErrAuth= 4,
  ErrACL= 5
};
}

/**
 * @enum {number}
 */
export namespace SelfMessaging{
export enum MsgType{
  MSG= 0,
  ACK= 1,
  ERR= 2,
  AUTH= 3,
  ACL= 4
};
}

/**
 * @enum {number}
 */
export namespace SelfMessaging{
export enum MsgSubType{
  Unknown= 0,
  AuthenticationReq= 1,
  AuthenticationResp= 2,
  AuthenticationQRResp= 3,
  AuthenticationDeepLinkResp= 4,
  FactReq= 5,
  FactResp= 6,
  FactQRResp= 7,
  FactDeepLinkResp= 8,
  EmailSecurityCodeReq= 9,
  EmailSecurityCodeResp= 10,
  PhoneSecurityCodeReq= 11,
  PhoneSecurityCodeResp= 12,
  PhoneVerificationReq= 13,
  PhoneVerificationResp= 14,
  EmailVerificationReq= 15,
  EmailVerificationResp= 16,
  DocumentVerificationReq= 17,
  DocumentVerificationResp= 18
};
}

/**
 * @constructor
 */
export namespace SelfMessaging{
export class Notification {
  bb: flatbuffers.ByteBuffer|null = null;

  bb_pos:number = 0;
/**
 * @param number i
 * @param flatbuffers.ByteBuffer bb
 * @returns Notification
 */
__init(i:number, bb:flatbuffers.ByteBuffer):Notification {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param flatbuffers.ByteBuffer bb
 * @param Notification= obj
 * @returns Notification
 */
static getRootAsNotification(bb:flatbuffers.ByteBuffer, obj?:Notification):Notification {
  return (obj || new Notification()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param flatbuffers.ByteBuffer bb
 * @param Notification= obj
 * @returns Notification
 */
static getSizePrefixedRootAsNotification(bb:flatbuffers.ByteBuffer, obj?:Notification):Notification {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new Notification()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param flatbuffers.Encoding= optionalEncoding
 * @returns string|Uint8Array|null
 */
id():string|null
id(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
id(optionalEncoding?:any):string|Uint8Array|null {
  var offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @returns SelfMessaging.MsgType
 */
msgtype():SelfMessaging.MsgType {
  var offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? /**  */ (this.bb!.readInt8(this.bb_pos + offset)) : SelfMessaging.MsgType.MSG;
};

/**
 * @param flatbuffers.Encoding= optionalEncoding
 * @returns string|Uint8Array|null
 */
error():string|null
error(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
error(optionalEncoding?:any):string|Uint8Array|null {
  var offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @returns SelfMessaging.ErrType
 */
errtype():SelfMessaging.ErrType {
  var offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? /**  */ (this.bb!.readInt8(this.bb_pos + offset)) : SelfMessaging.ErrType.ErrConnection;
};

/**
 * @param flatbuffers.Builder builder
 */
static startNotification(builder:flatbuffers.Builder) {
  builder.startObject(4);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset idOffset
 */
static addId(builder:flatbuffers.Builder, idOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, idOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @param SelfMessaging.MsgType msgtype
 */
static addMsgtype(builder:flatbuffers.Builder, msgtype:SelfMessaging.MsgType) {
  builder.addFieldInt8(1, msgtype, SelfMessaging.MsgType.MSG);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset errorOffset
 */
static addError(builder:flatbuffers.Builder, errorOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, errorOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @param SelfMessaging.ErrType errtype
 */
static addErrtype(builder:flatbuffers.Builder, errtype:SelfMessaging.ErrType) {
  builder.addFieldInt8(3, errtype, SelfMessaging.ErrType.ErrConnection);
};

/**
 * @param flatbuffers.Builder builder
 * @returns flatbuffers.Offset
 */
static endNotification(builder:flatbuffers.Builder):flatbuffers.Offset {
  var offset = builder.endObject();
  return offset;
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset offset
 */
static finishNotificationBuffer(builder:flatbuffers.Builder, offset:flatbuffers.Offset) {
  builder.finish(offset);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset offset
 */
static finishSizePrefixedNotificationBuffer(builder:flatbuffers.Builder, offset:flatbuffers.Offset) {
  builder.finish(offset, undefined, true);
};

static createNotification(builder:flatbuffers.Builder, idOffset:flatbuffers.Offset, msgtype:SelfMessaging.MsgType, errorOffset:flatbuffers.Offset, errtype:SelfMessaging.ErrType):flatbuffers.Offset {
  Notification.startNotification(builder);
  Notification.addId(builder, idOffset);
  Notification.addMsgtype(builder, msgtype);
  Notification.addError(builder, errorOffset);
  Notification.addErrtype(builder, errtype);
  return Notification.endNotification(builder);
}
}
}
