// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';
/**
 * @enum {number}
 */
export namespace SelfMessaging{
export enum ACLCommand{
  LIST= 0,
  PERMIT= 1,
  REVOKE= 2
};
}

/**
 * @enum {number}
 */
export namespace SelfMessaging{
export enum ErrType{
  ErrConnection= 0,
  ErrBadRequest= 1,
  ErrInternal= 2,
  ErrMessage= 3,
  ErrAuth= 4,
  ErrACL= 5
};
}

/**
 * @enum {number}
 */
export namespace SelfMessaging{
export enum MsgType{
  MSG= 0,
  ACK= 1,
  ERR= 2,
  AUTH= 3,
  ACL= 4
};
}

/**
 * @enum {number}
 */
export namespace SelfMessaging{
export enum MsgSubType{
  Unknown= 0,
  AuthenticationReq= 1,
  AuthenticationResp= 2,
  AuthenticationQRResp= 3,
  AuthenticationDeepLinkResp= 4,
  FactReq= 5,
  FactResp= 6,
  FactQRResp= 7,
  FactDeepLinkResp= 8,
  EmailSecurityCodeReq= 9,
  EmailSecurityCodeResp= 10,
  PhoneSecurityCodeReq= 11,
  PhoneSecurityCodeResp= 12,
  PhoneVerificationReq= 13,
  PhoneVerificationResp= 14,
  EmailVerificationReq= 15,
  EmailVerificationResp= 16,
  DocumentVerificationReq= 17,
  DocumentVerificationResp= 18
};
}

