"use strict";
// automatically generated by the FlatBuffers compiler, do not modify
exports.__esModule = true;
exports.SelfMessaging = void 0;
/**
 * @enum {number}
 */
var SelfMessaging;
(function (SelfMessaging) {
    var ACLCommand;
    (function (ACLCommand) {
        ACLCommand[ACLCommand["LIST"] = 0] = "LIST";
        ACLCommand[ACLCommand["PERMIT"] = 1] = "PERMIT";
        ACLCommand[ACLCommand["REVOKE"] = 2] = "REVOKE";
    })(ACLCommand = SelfMessaging.ACLCommand || (SelfMessaging.ACLCommand = {}));
    ;
})(SelfMessaging = exports.SelfMessaging || (exports.SelfMessaging = {}));
/**
 * @enum {number}
 */
(function (SelfMessaging) {
    var ErrType;
    (function (ErrType) {
        ErrType[ErrType["ErrConnection"] = 0] = "ErrConnection";
        ErrType[ErrType["ErrBadRequest"] = 1] = "ErrBadRequest";
        ErrType[ErrType["ErrInternal"] = 2] = "ErrInternal";
        ErrType[ErrType["ErrMessage"] = 3] = "ErrMessage";
        ErrType[ErrType["ErrAuth"] = 4] = "ErrAuth";
        ErrType[ErrType["ErrACL"] = 5] = "ErrACL";
    })(ErrType = SelfMessaging.ErrType || (SelfMessaging.ErrType = {}));
    ;
})(SelfMessaging = exports.SelfMessaging || (exports.SelfMessaging = {}));
/**
 * @enum {number}
 */
(function (SelfMessaging) {
    var MsgType;
    (function (MsgType) {
        MsgType[MsgType["MSG"] = 0] = "MSG";
        MsgType[MsgType["ACK"] = 1] = "ACK";
        MsgType[MsgType["ERR"] = 2] = "ERR";
        MsgType[MsgType["AUTH"] = 3] = "AUTH";
        MsgType[MsgType["ACL"] = 4] = "ACL";
    })(MsgType = SelfMessaging.MsgType || (SelfMessaging.MsgType = {}));
    ;
})(SelfMessaging = exports.SelfMessaging || (exports.SelfMessaging = {}));
/**
 * @enum {number}
 */
(function (SelfMessaging) {
    var MsgSubType;
    (function (MsgSubType) {
        MsgSubType[MsgSubType["Unknown"] = 0] = "Unknown";
        MsgSubType[MsgSubType["AuthenticationReq"] = 1] = "AuthenticationReq";
        MsgSubType[MsgSubType["AuthenticationResp"] = 2] = "AuthenticationResp";
        MsgSubType[MsgSubType["AuthenticationQRResp"] = 3] = "AuthenticationQRResp";
        MsgSubType[MsgSubType["AuthenticationDeepLinkResp"] = 4] = "AuthenticationDeepLinkResp";
        MsgSubType[MsgSubType["FactReq"] = 5] = "FactReq";
        MsgSubType[MsgSubType["FactResp"] = 6] = "FactResp";
        MsgSubType[MsgSubType["FactQRResp"] = 7] = "FactQRResp";
        MsgSubType[MsgSubType["FactDeepLinkResp"] = 8] = "FactDeepLinkResp";
        MsgSubType[MsgSubType["EmailSecurityCodeReq"] = 9] = "EmailSecurityCodeReq";
        MsgSubType[MsgSubType["EmailSecurityCodeResp"] = 10] = "EmailSecurityCodeResp";
        MsgSubType[MsgSubType["PhoneSecurityCodeReq"] = 11] = "PhoneSecurityCodeReq";
        MsgSubType[MsgSubType["PhoneSecurityCodeResp"] = 12] = "PhoneSecurityCodeResp";
        MsgSubType[MsgSubType["PhoneVerificationReq"] = 13] = "PhoneVerificationReq";
        MsgSubType[MsgSubType["PhoneVerificationResp"] = 14] = "PhoneVerificationResp";
        MsgSubType[MsgSubType["EmailVerificationReq"] = 15] = "EmailVerificationReq";
        MsgSubType[MsgSubType["EmailVerificationResp"] = 16] = "EmailVerificationResp";
        MsgSubType[MsgSubType["DocumentVerificationReq"] = 17] = "DocumentVerificationReq";
        MsgSubType[MsgSubType["DocumentVerificationResp"] = 18] = "DocumentVerificationResp";
    })(MsgSubType = SelfMessaging.MsgSubType || (SelfMessaging.MsgSubType = {}));
    ;
})(SelfMessaging = exports.SelfMessaging || (exports.SelfMessaging = {}));
