name: _build

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: node:18.15.0-bullseye
    steps:
      - name: Setup job
        uses: joinself/github-actions-public/setup-job@main
      - name: Build
        shell: bash
        run: |
          . ${GITHUB_WORKSPACE}/.ci/env
          apt-get update
          apt-get install -y python-is-python3
          npm install
          npm run lint
          npm run test
          npm run build
          tar -czf artifacts.tar.gz dist
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: artifacts
          path: artifacts.tar.gz
          retention-days: 1
      - name: Failure notification
        if: ${{ github.ref == 'refs/heads/main' && failure() }}
        uses: joinself/github-actions-public/failure-notification@main
        with:
          slack-webhook: ${{ secrets.SLACK_WEBHOOK_CI_ALERTS }}
