name: CI

on: [push, pull_request, workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-20.04

    container:
      image: ubuntu:focal-20210217
      env:
        DEBIAN_FRONTEND: noninteractive

    steps:
      - uses: actions/checkout@v2

      - name: Setup environment
        shell: bash -l {0}
        run: |
          apt-get update
          apt-get -y install curl libsodium-dev npm
          curl https://download.joinself.com/olm/libself-olm_0.1.17_amd64.deb -o /tmp/libself-olm_0.1.17_amd64.deb
          curl https://download.joinself.com/omemo/libself-omemo_0.1.3_amd64.deb -o /tmp/libself-omemo_0.1.3_amd64.deb
          apt-get -y install /tmp/libself-olm_0.1.17_amd64.deb
          apt-get -y install /tmp/libself-omemo_0.1.3_amd64.deb
          npm install
          cat /etc/issue
          echo $SHELL
          pwd
          whoami
          node -v
          npm -v
          npm test
