name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  license-compliance:
    uses: joinself/github-workflows-public/.github/workflows/license-compliance.yml@main
    with:
      container-image: joinself/license-finder:node
      continue-on-error: true
    secrets: inherit
  build:
    needs: license-compliance
    uses: ./.github/workflows/build.yml
    secrets: inherit
  publish:
    if: ${{ github.ref == 'refs/heads/main' }}
    needs: build
    uses: ./.github/workflows/publish.yml
    secrets: inherit
