name: CI

on: 
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:22.04
      env:
        DEBIAN_FRONTEND: noninteractive
    steps:
      - uses: actions/checkout@v3
      - name: Setup environment
        run: |
          apt-get update
          apt-get -y install curl libsodium-dev npm
      - name: Install dependencies
        run: npm install
      - name: Build package
        run: npm run build
      - name: Test package
        run: npm run test
